### ISSUE TITLE
Option to use system site for reordering

### ISSUE THREAD

**Issue by karlicoss** [seanbreckenridge/reorder_editable#3]
I'm trying to use latest python via [pyenv](https://github.com/pyenv/pyenv) on my macos, and it maintains a separate package hierarchy in home directory, so seems like a more 'canonical' way to use it is to just install packages as `pip install`, without `--user`.

```
In [2]: import site

In [3]: site.getusersitepackages()
Out[3]: '/Users/karlicos/.local/lib/python3.11/site-packages'

In [4]: site.getsitepackages()
Out[4]: ['/Users/karlicos/.pyenv/versions/3.11.2/lib/python3.11/site-packages']
```

At the moment can use `--easy-install-location`, but perhaps for less typing would make sense to add an option to use system site. It seems like it's a list 🤔 so not sure what to do in general case (e.g. for 'system' python it does contains multiple paths). But for now I think could just slap an assert that it's a single element list, which would likely be always the case for 'virtualenvish' sites like this one.

I guess that would require a cli flag and checking it here: 
https://github.com/seanbreckenridge/reorder_editable/blob/11309e42ddc89a3422e5743d951930503f88f1b7/reorder_editable/core.py#L165
I think it makes sense to add both `--user` and `--system`, and just keep default as `--user` for backwards compatibility.

Another small suggestion is perhaps it would be useful to print the path to `easy-install.pth` used during `reorder-editable reorder` command so the user doesn't have to figure out and call `reorder-editable locate` (perhaps could do same same for `cat`). 

Happy to do both if you think that makes sense!

**Comment by seanbreckenridge** [comment]
yeah those changes sound good to me.

Had this note in the readme:

> Either install all editable packages as --user, or all at the system level. Otherwise, the lines of text/packages are split across two separate easy-install.pth files, and its not possible to reorder

hadnt really considered in a virtualenv that it would be installing in the 'system site' directory, I tend to use the globally installed python (though have been moving more to just using `virtualenv` for projects recently, maybe should do that in general)

glad to accept a PR for your usecase

**Comment by seanbreckenridge** [comment]
> Another small suggestion is perhaps it would be useful to print the path to easy-install.pth

As long as it can be disabled through a flag/envvar, sure

**Comment by karlicoss** [comment]
> can add a --debug flag and propogate that through to everywhere if you'd like (default to on?), or just --print-location/--dont-print-location and print it in __main__

hmm, is there any downside of printning it by default in `_print_editable_contents`? It does it to stderr, so won't break any tools which might expect a certain format?
